
modLoader="javafml"
loaderVersion="[34,)"
license="The Unlicense"

[[mods]]
    modId="moremetals"
    version="${file.jarVersion}"
    displayName="More Metals"
    # logoFile="examplemod.png"
    credits="Thanks for this mod goes to Deathstructor"
    authors="Deathstructor"
    description='''
    A mod that adds more metals to the game, including tools, weapons and armor.
    '''

[[dependencies.moremetals]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moremetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17]"
    ordering="NONE"
    side="BOTH"
